version: '3.9'

services:
  db:
    build:
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "3307:3306"
    container_name: db
  web:
    build:
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - db
    ports:
      - "9090:8080"
    container_name: server
