version: '3.8'

services:
  db:
    image: mysql:latest
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    container_name: prolog_db
  web:
      depends_on:
        - db
      image: tomcat:9.0.36
      volumes:
        - ./build/lib:/usr/local/tomcat/webapps
      ports:
        - "9090:8080"
      environment:
        MYSQL_ROOT_PASSWORD: password
      container_name: prolog_server
